"""Seed claim registry for NeuroDecide-Bench-lite."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ClaimLibraryEntry:
    """One benchmark claim-library entry."""

    contract_path: str
    ground_truth_status: str
    ref_effect: float | None
    source: str


REGISTRY: list[ClaimLibraryEntry] = [
    ClaimLibraryEntry(
        contract_path="configs/contracts/example_age_atrophy.yaml",
        ground_truth_status="positive",
        # TODO(confirm): Replace with a meta-analytic reference effect size and citation.
        ref_effect=None,
        source="TODO(confirm): cite aging cortical-thickness meta-analysis.",
    ),
    ClaimLibraryEntry(
        contract_path="configs/contracts/asd_single_site_fragile.yaml",
        ground_truth_status="fragile",
        # TODO(confirm): Replace with a curated reference effect size and citation.
        ref_effect=None,
        source="TODO(confirm): cite ASD case-control neuroimaging reference.",
    ),
    ClaimLibraryEntry(
        contract_path="configs/contracts/injected_null.yaml",
        ground_truth_status="null",
        # TODO(confirm): Injected-null tasks have no biological reference effect.
        ref_effect=None,
        source="Synthetic injected null generated by src/bench/injected_nulls.py.",
    ),
]


def lookup_ref_effect(contract_path: str | Path, claim_id: str | None = None) -> float | None:
    """Return the registered reference effect for a contract, if known."""

    path = str(contract_path)
    for entry in REGISTRY:
        if entry.contract_path == path or Path(entry.contract_path).name == Path(path).name:
            return entry.ref_effect
    if claim_id:
        for entry in REGISTRY:
            if claim_id in Path(entry.contract_path).stem:
                return entry.ref_effect
    return None

