"""Benchmark scoring labels and authoritative claim-label table access.

The label table separates scientific/adjudication metadata from gate outcomes.
Small expected RSFC-cognition effects are not scored as false confirmations,
while known-null and fragile claims are both counted in FCR.
"""

from __future__ import annotations

import csv
from functools import lru_cache
from pathlib import Path
from typing import Any


LABEL_TABLE_PATH = Path(__file__).resolve().parents[2] / "data" / "labels" / "claim_label_table.csv"

LABEL_TABLE_COLUMNS = [
    "claim_id",
    "phenotype",
    "modality",
    "cohorts",
    "discovery_cohort",
    "replication_cohort",
    "label_class",
    "label_basis",
    "adjudication_status",
    "expected_direction",
    "expected_effect_scale",
    "mde_assumption",
    "cohort_role",
    "forbidden_evidence",
    "confound_set",
    "site_scanner_handling",
    "decision_target",
    "construct_validity_notes",
    "label_confidence",
    "source_citation",
]

LABEL_CLASSES = {
    "known_positive",
    "known_null",
    "fragile",
    "underpowered_small_positive",
    "candidate_unknown",
}

LABEL_BASES = {
    "meta_analysis",
    "large_cohort_replication",
    "canonical_literature",
    "synthetic_stress",
    "internal_split_half",
}

MAIN_LABEL_BASES = {"meta_analysis", "large_cohort_replication", "canonical_literature"}

ADJUDICATION_STATUSES = {
    "preregistered",
    "expert_adjudicated",
    "author_assigned",
    "provisional",
}

FMRI_SCORING_LABELS: dict[str, str] = {
    "age_fc_ukb_hcpaging": "positive_stability",
    "age_fc_hcpa_hcp": "positive_stability",
    "sex_fc_ukb_hcp": "positive_stability",
    "sex_fc_abcd_hcp": "positive_stability_cross_age_stress",
    "cognition_fc_ukb_abcd": "small_positive_expected",
    "cognition_fc_hcp_hcpa": "small_positive_expected_or_underpowered",
    "cognition_dyno_ukb_abcd": "small_positive_candidate",
    "adhd_fc_adhd200_abcd": "fragile_candidate",
    "adhd_region_adhd200_abcd": "fragile_candidate",
    "asd_fc_abide2_abcd": "fragile_candidate",
    "ad_fc_adni_oasis3": "positive_or_fragile_candidate",
    "ad_region_adni_oasis3": "positive_or_fragile_candidate",
    "ad_dyno_adni_oasis3": "positive_or_fragile_candidate",
    "injected_null_site_abcd": "known_null_synthetic",
    "injected_null_site_ukb": "known_null_synthetic",
    "injected_null_random_hcp": "known_null_synthetic",
    "injected_null_fishing_abide2": "known_null_synthetic",
    "injected_null_fishing_adhd200": "known_null_synthetic",
    "underpowered_asd_site_abide2": "stress_test_fragile",
    "underpowered_adhd_site_adhd200": "stress_test_fragile",
}


LABEL_PROVENANCE: dict[str, str] = {
    "known_null": "Known-null or synthetic-null label registered in data/labels/claim_label_table.csv.",
    "fragile": "Fragile/stress label registered in data/labels/claim_label_table.csv; confirmations count in FCR.",
    "underpowered_small_positive": "Small expected positive label registered separately from FCR.",
    "candidate_unknown": "Candidate/provisional claim not scored as known positive or known negative.",
    "known_positive": "Externally established positive-control label from canonical biomarker or stability literature.",
    "positive_stability": "Biological/stability positive-control label; not a disease-biomarker claim.",
    "positive_stability_cross_age_stress": "Biological/stability positive-control label with deliberate cross-age generalization stress.",
    "small_positive_expected": "Small but expected brain-behavior effect; scored separately from FCR.",
    "small_positive_expected_or_underpowered": "Small expected effect where non-confirmation can be acceptable because power/generalization may be weak.",
    "small_positive_candidate": "Plausible small-effect candidate; scored separately from FCR and TPR.",
    "known_null_synthetic": "Synthetic injected-null label generated by benchmark construction.",
    "stress_test_fragile": "Designed stress-test claim; counts in paper-facing FCR but not as a literature-null biomarker.",
    "fragile_candidate": "Plausible but heterogeneous disease/cross-cohort candidate; scored separately from FCR.",
    "positive_or_fragile_candidate": "Plausible positive candidate without enough adjudication for paper-facing TPR.",
    "candidate": "Unadjudicated candidate label; scored separately.",
}


def validate_claim_label_table(rows: list[dict[str, str]]) -> None:
    """Validate the authoritative claim-label table schema and core enums."""

    if not rows:
        raise ValueError("Claim label table is empty")
    seen: set[str] = set()
    for i, row in enumerate(rows, start=2):
        missing = [col for col in LABEL_TABLE_COLUMNS if col not in row]
        if missing:
            raise ValueError(f"Claim label table row {i} missing columns: {missing}")
        blank = [col for col in LABEL_TABLE_COLUMNS if str(row.get(col, "")).strip() == ""]
        if blank:
            raise ValueError(f"Claim label table row {i} has blank required fields: {blank}")
        claim_id = row["claim_id"].strip()
        if claim_id in seen:
            raise ValueError(f"Duplicate claim_id in claim label table: {claim_id}")
        seen.add(claim_id)
        if row["label_class"] not in LABEL_CLASSES:
            raise ValueError(f"Invalid label_class for {claim_id}: {row['label_class']}")
        if row["label_basis"] not in LABEL_BASES:
            raise ValueError(f"Invalid label_basis for {claim_id}: {row['label_basis']}")
        if row["adjudication_status"] not in ADJUDICATION_STATUSES:
            raise ValueError(f"Invalid adjudication_status for {claim_id}: {row['adjudication_status']}")


def source_citation_is_real_reference(source_citation: str | None) -> bool:
    """Return true only for non-placeholder citation strings."""

    citation = str(source_citation or "").strip().lower()
    if not citation:
        return False
    if citation in {"provisional", "verify", "[verify]", "none", "n/a", "na", "unknown", "tbd"}:
        return False
    return "provisional" not in citation and "[verify]" not in citation


def label_authority(row: dict[str, str]) -> str:
    """Partition a label-table row into MAIN or SUPPLEMENTARY authority."""

    status = str(row.get("adjudication_status", "")).strip()
    if status in {"author_assigned", "provisional"}:
        return "supplementary"
    if status in {"preregistered", "expert_adjudicated"}:
        return "main"
    if (
        str(row.get("label_basis", "")).strip() in MAIN_LABEL_BASES
        and source_citation_is_real_reference(row.get("source_citation"))
    ):
        return "main"
    return "supplementary"


@lru_cache(maxsize=8)
def load_claim_label_table(path: str | Path = LABEL_TABLE_PATH) -> dict[str, dict[str, str]]:
    """Load and validate the authoritative claim-label table."""

    src = Path(path)
    with src.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames != LABEL_TABLE_COLUMNS:
            raise ValueError(f"Unexpected claim label table columns: {reader.fieldnames}")
        rows = [{key: str(value).strip() for key, value in row.items()} for row in reader]
    validate_claim_label_table(rows)
    for row in rows:
        row["label_authority"] = label_authority(row)
    return {row["claim_id"]: row for row in rows}


def load_label_table(path: str | Path = LABEL_TABLE_PATH) -> dict[str, dict[str, str]]:
    """Compatibility alias for the authoritative claim-label table loader."""

    return load_claim_label_table(path)


def validate_label_coverage(
    claim_ids: list[str] | set[str] | tuple[str, ...],
    table: dict[str, dict[str, str]] | None = None,
    *,
    context: str = "scored claims",
) -> None:
    """Fail if any scored claim ID lacks an authoritative label-table row."""

    labels = load_claim_label_table() if table is None else table
    missing = sorted({str(claim_id).strip() for claim_id in claim_ids if str(claim_id).strip()} - set(labels))
    if missing:
        raise ValueError(f"Missing claim-label table rows for {context}: {missing}")


def claim_label_for_claim(claim: Any, table: dict[str, dict[str, str]] | None = None) -> dict[str, str] | None:
    """Return the authoritative table row for a claim if one is registered."""

    get = claim.get if hasattr(claim, "get") else lambda key, default=None: getattr(claim, key, default)
    claim_id = str(get("claim_id", "")).strip()
    labels = load_claim_label_table() if table is None else table
    return labels.get(claim_id)


def scoring_label_for_claim(claim: Any, *, require_table: bool = True) -> str:
    """Return the label used for benchmark scoring."""

    get = claim.get if hasattr(claim, "get") else lambda key, default=None: getattr(claim, key, default)
    claim_id = str(get("claim_id", ""))
    table_row = claim_label_for_claim(claim)
    if table_row is not None:
        return table_row["label_class"]
    if require_table:
        raise ValueError(f"Missing claim-label table row for scored claim_id: {claim_id}")
    if claim_id in FMRI_SCORING_LABELS:
        return FMRI_SCORING_LABELS[claim_id]

    expected = str(get("expected_label", "")).lower()
    claim_type = str(get("claim_type", "")).lower()
    if "null" in expected:
        return "known_null_synthetic" if claim_type == "injected_null" else "known_null"
    if "underpowered" in expected or "underpowered" in claim_type:
        return "stress_test_fragile"
    if expected in {"positive", "known_positive"} or claim_type == "known_positive":
        return "known_positive"
    if "small" in expected:
        return "small_positive_expected"
    if "fragile" in expected:
        return "fragile_candidate"
    if "positive" in expected:
        return "positive_or_fragile_candidate" if "fragile" in expected else "candidate"
    return "candidate"


def scoring_bucket(label: str) -> str:
    """Map a detailed scoring label to a metric bucket."""

    if label in {"known_positive", "positive", "positive_stability", "positive_stability_cross_age_stress"}:
        return "positive"
    if label in {"known_null", "known_null_synthetic", "stress_test_fragile", "fragile"}:
        return "negative"
    if label.startswith("small_positive") or label == "underpowered_small_positive":
        return "small_positive"
    return "candidate"


def label_provenance(label: str) -> str:
    return LABEL_PROVENANCE.get(label, LABEL_PROVENANCE["candidate"])
